"""initial

Revision ID: 71a4f221ba5a
Revises: 
Create Date: 2026-08-01 23:34:10.019385
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '71a4f221ba5a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_fingerprint'), 'jobs', ['fingerprint'], unique=True)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('reasons', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('red_flags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_job_id'), 'matches', ['job_id'], unique=False)
    op.create_index(op.f('ix_matches_score'), 'matches', ['score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_score'), table_name='matches')
    op.drop_index(op.f('ix_matches_job_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_jobs_fingerprint'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
